options = {
    validator: {
        $jsonSchema: {
            required: ["title"],
            properties: {
                title: {
                    bsonType: "string",
                    minLength: 1,
                },
                year: {
                    bsonType: "int",
                    minimum: 1870,
                    maximum: 2500,
                },
                writers: {
                    bsonType: "array",
                    maxItems: 10,
                    items: {
                        bsonType: "string",
                    },
                },
                summary: { bsonType: "string" },
                franchise: { bsonType: "string" },
                runningTime: { bsonType: "int", maximum: 54000 },
                budget: { bsonType: "int", minimum: 0 },
                box_office: {
                    bsonType: "int",
                    minimum: 0,
                },
                actors: {
                    bsonType: "array",
                    maxItems: 20,
                    items: {
                        bsonType: "string",
                    },
                },
                directors: {
                    bsonType: "array",
                    maxItems: 10,
                    items: {
                        bsonType: "string",
                    },
                },
                genres: {
                    bsonType: "array",
                    maxItems: 10,
                    items: {
                        bsonType: "string",
                    },
                },
                imdb_id: { pattern: "^[a-z]{2}\d{7,}$" },
            },
        },
    },
};

db.films.insertOne({
    title: "Star Trek: Nemesis",
    year: 2002,
    writers: ["John Logan", "Rick Berman", "Brent Spiner"],
    summary:
        "A clone of Picard, created by the Romulans, assassinates the Romulan Senate, " +
        "assumes absolute power, and lures Picard and the Enterprise to Romulus " +
        "under the false pretext of a peace overture.",
});

db.films.insertMany([
    {
        title: "My Dearest Assassin",
        writers: ["Watthana Veerayawatthana"],
        actors: [
            "Pimchanok Luevisadpaibul",
            "Tor Thanapob Leeratanakachorn",
            "Sivakorn Adulsuttiku",
        ],
        year: 2026,
        running_time: 127,
        budget: 237000000,
        genre: ["Action", "Romance", "Thai", "Thriller", "Drama"],
    },
    {
        title: "Fictionally Fake Film",
    },
    {
        title: "You Cannae be Serious About a Fictional Film",
    },
]);

db.films.insertMany([
    {
        title: "Pride",
        year: 2014,
        writers: ["Stephen Beesform"],
        franchise: [],
        running_time: 192,
        imdb_rating: 7.8,
    },
    {
        title: "Pee Wee Herman's Big Adventure",
    },
    {
        title: "A Fictional Tale as a Fake Film",
    },
]);

// From: https://www.imdb.com/title/tt1170358/ (Desolation)

// From: https://www.imdb.com/title/tt0903624/ (Journey)

actorsSmaug = [
    "Frazer Anderson",
    "Michael Andrews",
    "Richard Armitage",
    "Mark Atkin",
    "Dimetrius Baccellia",
    "Jim Baltaxe",
    "Rodney Bane",
    "Leila Barber",
    "Dallas Barnett",
    "Nigel Bautista",
    "Cory Beeston",
    "Aleksandr Beliaev",
    "Bruce Bell",
    "John Bell",
    "Vivien Bell",
    "Manu Bennett",
    "Jack Binding",
    "Terry Binding",
    "Nick Blake",
    "Cate Blanchett",
    "Orlando Bloom",
    "Bruno Du Bois",
    "Dorothy Anne Bonner",
    "Geoff Boothby",
    "Shane Boulton",
    "Jed Brophy",
    "Riley Brophy",
    "Chris Brough",
    "Adam Brown",
    "Lincoln Brown",
    "Mel Buchanan",
    "Tessa Buchanan",
    "Jessica Buckham",
    "Tony Burton",
    "Rosalie Button",
    "John Callen",
    "Melanie Carrington",
    "Ron Chamberlain",
    "Colleen Cleary",
    "Evie McGee Colbert",
    "John Colbert",
    "Stephen Colbert",
    "Yvette Cottam",
    "Raymond Cox",
    "Paul Craze",
    "Benedict Cumberbatch",
    "Estere Dalton",
    "Brendan Dee",
    "Karl Dickson",
    "David Donaldson",
    "Alison Draine",
    "Brady Dyer",
    "Frank Edwards",
    "Greg Ellis",
    "David Evans",
    "Luke Evans",
    "Dave Fitzgerald",
    "Michael Fowler",
    "Ben Fransham",
    "Martin Freeman",
    "Gary French",
    "Stephen Fry",
    "Ryan Gage",
    "Paul Gaudin",
    "Phoebe Gittins",
    "Tim Gordon",
    "Stephen Grey",
    "Mark Hadlow",
    "Craig Hall",
    "Peter Hambleton",
    "George Harach",
    "Nigel Harbrow",
    "Jamie Harrison",
    "Luke Hawker",
    "Ray Henwood",
    "Annie van Herck",
    "Ajala Hesketh",
    "Chimtamani Hesketh",
    "Fraser Hesketh",
    "Maitreya Hesketh",
    "Sanjaia Hesketh",
    "Chris Hewer",
    "Keirryn Hintz",
    "Christian Hipolito",
    "Kathryn Briggs Hobbs",
    "Fataneh Howe",
    "John Howe",
    "Martin Howells",
    "Stephen Hunter",
    "Alex Ishikawa",
    "Gideon Jack",
    "Katherine Jackson",
    "Peter Jackson",
    "Erana James",
    "Ben Johnson-Frow",
    "Raymond Jones",
    "Norman Kali",
    "Fern Karun",
    "K.C. Kelly",
    "Eli Kent",
    "Robin Kerr",
    "Gustav Kessel",
    "Taniora Kidwell",
    "Kelly Kilgour",
    "Isabelle Rose Kircher",
    "William Kircher",
    "Kristi Kleijn",
    "Dean Knowsley",
    "Simon Leary",
    "Alan Lee",
    "Evangeline Lilly",
    "Simon London",
    "Phil Mackie",
    "Lawrence Makoare",
    "Asofa Manase",
    "Heli Matilainen",
    "Simon McArthur",
    "Sylvester McCoy",
    "Steve McDonald",
    "Peter McGee",
    "Walter McGinnis",
    "Shirley McGregor",
    "Dra McKay",
    "Ian McKellen",
    "Dallas McKinley",
    "Carlton McRae",
    "Graham McTavish",
    "Ceci Mediano",
    "Sebastian Meek",
    "Liz Merton",
    "Iain Middleton",
    "Joseph Mika-Hunt",
    "Ben Mitchell",
    "Mark Mitchinson",
    "Keith Mole",
    "Linda Murrell",
    "Ravi Narayan",
    "James Nesbitt",
    "Mary Nesbitt",
    "Peggy Nesbitt",
    "Jimmy James Nielsen",
    "Carter Nixon",
    "Terry Notary",
    "Wesley O'Duinn",
    "Dean O'Gorman",
    "Stephen O'Neill",
    "Kyosuke Okada",
    "Jabez Olssen",
    "Lee Pace",
    "Ivy Padilla",
    "Karen Palmer",
    "Mark Pearson",
    "Sarah Peirse",
    "Lise Perichon",
    "Mikael Persbrandt",
    "Wayne Phillips",
    "Derek Price",
    "Dinah Priestley",
    "Stan the Wonder Pug",
    "Nicolas Pye",
    "Paul Randall",
    "Shane Rangi",
    "Daniel Rathbon",
    "Leon Reedijk",
    "Phil Reilly",
    "Adebisi Riwanou",
    "Tom Robinson",
    "Steve Roche",
    "Gabriela Roque-Worcel",
    "Warwick Sadler",
    "Michelle Scullion",
    "Chromatic Semitone",
    "Brian Sergent",
    "Kiran Shah",
    "Tony Shaw",
    "Ed Sheeran",
    "Antony Sher",
    "Fiona Simpson",
    "Tim Simpson",
    "Bruce Sinclair",
    "Marco Sinigaglia",
    "Jeff Slaven",
    "Allan Smith",
    "Dianne Smith",
    "Emma Smith",
    "Matt Smith",
    "Ziggy Stiles",
    "Ken Stott",
    "Ken Stratton",
    "Hannah Tasker-Poland",
    "Jennifer Tebbs",
    "Jeffrey Thomas",
    "Karen Thompson",
    "Royd Tolkien",
    "Mark Trotter",
    "Aidan Turner",
    "Lee Tuson",
    "Stephen Ure",
    "Karl Vader",
    "Peter Vere-Jones",
    "Manuela Vetters",
    "Chase Voss",
    "James Waterhouse-Brown",
    "Allan John Webb",
    "Zane Weiner",
    "Ruben Werle",
    "Richard Whiteside",
    "Alaina Wilks",
    "Chrissy Wilson",
    "Christopher Winchester",
    "Nikky Winchester",
    "Min Windle",
    "Teresa Winters",
    "Pedro Worcel",
    "Nigel Zega",
];

starsSmaug = ["Ian McKellen", "Martin Freeman", "Richard Armitage"];

starsJourney = ["Martin Freeman", "Ian McKellen", "Richard Armitage"];

db.films.insertMany([
    {
        title: "The Hobbit: The Desolation of Smaug",
        year: 2013,
        franchise: "The Hobbit",
        directors: ["Peter Jackson"],
        writers: [
            "Fran Walsh",
            "Philippa Boyens",
            "Peter Jackson",
            "Guillermo del Toro",
            "J.R.R. Tolkien",
        ],
        actors: starsSmaug,
        imdb_id: "tt1170358",
        imdb_rating: 7.8,
    },
    {
        title: "The Hobbit: An Unexpected Journey",
        year: 2012,
        franchise: "The Hobbit",
        directors: ["Peter Jackson"],
        writers: ["Fran Walsh", "Philippa Boyens", "Peter Jackson"],
        actors: startsJourney,
        imdb_id: "tt0903624",
        imdb_rating: 7.8,
    },
]);

db.films.updateOne(
    { title: "Pulp Fiction" },
    { $addToSet: { actor: "Samuel L. Jackson" } },
);
db.films.updateOne(
    { title: "Star Trek: Nemesis" },
    {
        $push: {
            actors: {
                $each: [
                    "Patrick Stewart",
                    "Jonathan Frakes",
                    "Brent Spiner",
                    "LeVar Burton",
                    "Michael Dorn",
                    "Gates McFadden",
                    "Marina Sirtis",
                ],
            },
        },
    },
);

db.films.deleteOne({
    title: "Pee Wee Herman's Big Adventure",
});

result = db.films.findOne({ title: "Fictionally Fake Film" });
db.films.deteteOne(result._id);

